-- ============================================================================
-- ATS SAAS · Fase 1 · Catálogo inicial de categorías de costo
-- Extraído de la hoja "Base_Categorías" del Excel original.
-- ============================================================================

insert into public.categorias_costo (categoria, subcategoria) values
  ('Combustible', 'Diésel'),
  ('Combustible', 'Gasolina'),
  ('Combustible', 'AdBlue'),
  ('Mantención', 'Preventiva'),
  ('Mantención', 'Correctiva'),
  ('Mantención', 'Lubricantes'),
  ('Mantención', 'Hidráulica'),
  ('Mantención', 'Frenos'),
  ('Repuestos', 'Neumáticos'),
  ('Repuestos', 'Baterías'),
  ('Repuestos', 'Accesorios'),
  ('Repuestos', 'Herramientas'),
  ('Repuestos', 'Filtros'),
  ('TAG y Peajes', 'Autopistas urbanas'),
  ('TAG y Peajes', 'Rutas interurbanas'),
  ('TAG y Peajes', 'Multas por TAG'),
  ('Sueldos Operativos', 'Choferes'),
  ('Sueldos Operativos', 'Operadores'),
  ('Sueldos Operativos', 'Ayudantes'),
  ('Sueldos Operativos', 'Gratificaciones'),
  ('Viáticos', 'Alojamiento'),
  ('Viáticos', 'Alimentación'),
  ('Viáticos', 'Movilización'),
  ('Arriendo Maquinaria', 'Grúas adicionales'),
  ('Arriendo Maquinaria', 'Camiones externos'),
  ('Arriendo Maquinaria', 'Equipos de izaje'),
  ('Transporte Externo', 'Subcontratos'),
  ('Uniformes y EPP', 'Ropa de trabajo'),
  ('Uniformes y EPP', 'Botas'),
  ('Uniformes y EPP', 'Casco'),
  ('Uniformes y EPP', 'Chaleco'),
  ('Otros Operacionales', 'Insumos varios'),
  ('Honorarios', 'Contabilidad'),
  ('Honorarios', 'Abogado'),
  ('Honorarios', 'Prevencionista'),
  ('Honorarios', 'Ingeniería externa'),
  ('Honorarios', 'Notaría'),
  ('Honorarios', 'Administrativo'),
  ('Servicios Básicos', 'Luz'),
  ('Servicios Básicos', 'Agua'),
  ('Servicios Básicos', 'Internet'),
  ('Servicios Básicos', 'Telefonía'),
  ('Arriendos', 'Oficina'),
  ('Arriendos', 'Bodega'),
  ('Arriendos', 'Terreno'),
  ('Gastos Bancarios', 'Comisiones'),
  ('Gastos Bancarios', 'Mantenciones de cuenta'),
  ('Gastos Bancarios', 'Transferencias'),
  ('Publicidad y Marketing', 'Publicidad en redes'),
  ('Publicidad y Marketing', 'Diseño gráfico'),
  ('Publicidad y Marketing', 'Impresiones'),
  ('Software y Licencias', 'ERP'),
  ('Software y Licencias', 'Control de flota'),
  ('Software y Licencias', 'Autocad'),
  ('Software y Licencias', 'Office'),
  ('Papelería y Útiles', 'Papelería general'),
  ('Capacitación', 'Cursos y licencias'),
  ('Capacitación', 'Certificación Pluma'),
  ('Representación', 'Comidas y reuniones'),
  ('Seguros', 'Seguro vehículos'),
  ('Seguros', 'Responsabilidad civil'),
  ('Seguros', 'Seguro empresa'),
  ('Otros Administrativos', 'Gastos menores'),
  ('Otros Administrativos', 'Pago IVA'),
  ('Vehículos', 'Camiones pluma'),
  ('Equipos de Izaje', 'Plumas hidráulicas'),
  ('Infraestructura', 'Contenedores y oficinas'),
  ('Equipamiento TI', 'Computadores y radios'),
  ('Software', 'ERP y software técnico'),
  ('Herramientas', 'Herramientas operativas'),
  ('Transporte especializado', 'Camión pluma'),
  ('Izaje y montaje', 'Maniobra en altura'),
  ('Ingeniería de apoyo', 'Supervisión técnica'),
  ('Arriendo con operador', 'Turno por hora'),
  ('Otros servicios', 'Apoyo en obra'),
  ('Servicios Externos', 'Supervisión técnica'),
  ('Servicios Externos', 'Transporte')
on conflict (categoria, subcategoria) do nothing;
